apiVersion: v1
kind: Pod
metadata:
  name: pod-practice
spec:
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.100.6
        path: /mnt/shared
    - name: emptydir-volume
      emptyDir: {}

  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
        - name:  emptydir-volume
          mountPath:  /usr/share/nginx/html
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 10
        periodSeconds: 10

    - name: siedcar-container
      image: busybox
     
      command: ["/bin/sh", "-c", "while true; do echo '<h1>Hello from sidecar</h1>' > /mnt/shared/index.html; sleep 10; done"]
      resources:
        requests:
          memory: "16Mi"
          cpu: "110m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: emptydir-volume     
          mountPath: /mnt/shared